# system defaults
ec2:
  region: "{{ aws_region | default('us-east-1') }}"
  node_type: 'ec2 instance'
packages:
  epel_version: '7-11'
  java_version: '1.8.0'
linux:
  limits:
    config_file: /etc/security/limits.conf
    soft:
      config:
        fsize:
        nofile: 1000000
        nproc:
        core:
        stack:
    hard:
      config:
        fsize:
        nofile: 1000000
        nproc:
        core:
        stack:
